return {
	[1] = { id = 1, macro = "DIG_TIME", name = "挖掘时间", },
	[2] = { id = 2, macro = "DIG_FREQ", name = "挖掘频率", },
	[3] = { id = 3, macro = "DIG_SOIL_PER", name = "每次挖掘量", },
	[4] = { id = 4, macro = "DIG_SPEED_UP", name = "提升挖矿速度", },
	[5] = { id = 5, macro = "PICK_SPEED_UP", name = "提升精炼速度", },
	[6] = { id = 6, macro = "POWER_UP", name = "提升算力", },
	[7] = { id = 7, macro = "STRONG_UP", name = "提升强壮", },
	[8] = { id = 8, macro = "TRICK_UP", name = "提升技巧", },
	[9] = { id = 9, macro = "DIG_SEAT_ADD", name = "增加挖矿派遣位", },
	[10] = { id = 10, macro = "PICK_SEAT_ADD", name = "增加精炼派遣位", },
	[11] = { id = 11, macro = "DIG_TIME_ADD", name = "增加挖矿时长", },
	[12] = { id = 12, macro = "PICK_TIME_ADD", name = "增加精炼时长", },
	[13] = { id = 13, macro = "DIG_TIME_CUT", name = "减少挖矿时间间隔", },
	[14] = { id = 14, macro = "PICK_TIME_CUT", name = "减少精炼时间间隔", },
	[15] = { id = 15, macro = "REWARD_STONE_UP", name = "提升原石获得概率", },
	[16] = { id = 16, macro = "REWARD_GOLD_UP", name = "提升黄金获得概率", },
	[17] = { id = 17, macro = "EXTRA_BONUS", name = "兑换矿币额外奖励", },
	[18] = { id = 18, macro = "EX_UP_COST_CUT", name = "减少交易所上架费用", },
	[19] = { id = 19, macro = "EX_COST_CUT", name = "减少交易所交易费用", },
	[20] = { id = 20, macro = "SHOP_DISCOUNT", name = "商城物品打折", },
	[21] = { id = 21, macro = "UPGRADE_TIME_CUT", name = "减少升星时间", },
	[22] = { id = 22, macro = "USED_SKILL", name = "自动使用主动技能", },
}
